---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
        name: 💄 Ensuring files are prettier
        types: [yaml, json, markdown]
  - repo: local
    hooks:
      - id: ruff-fmt
        name: ☕️ Format using ruff
        language: system
        types: [python]
        entry: 'uv run ruff format legow tests'
      - id: ruff-lint
        name: 🧪 Lint using ruff
        language: system
        types: [python]
        entry: 'uv run ruff check --fix legow tests'
      - id: mypy
        name: 🆎 Static type checking using mypy
        language: system
        types: [python]
        pass_filenames: false
        entry: 'uv run mypy legow --install-types --non-interactive --show-traceback'
      - id: check-ast
        name: 🐍 Check Python AST
        language: system
        types: [python]
        entry: uv run check-ast
      - id: check-case-conflict
        name: 🔠 Check for case conflicts
        language: system
        entry: uv run check-case-conflict
      - id: check-docstring-first
        name: ℹ️  Check docstring is first
        language: system
        types: [python]
        entry: uv run check-docstring-first
      - id: check-executables-have-shebangs
        name: 🧐 Check that executables have shebangs
        language: system
        types: [text, executable]
        entry: uv run check-executables-have-shebangs
        stages: [pre-commit, pre-push, manual]
      - id: check-json
        name: ｛ Check JSON files
        language: system
        types: [json]
        entry: uv run check-json
      - id: check-merge-conflict
        name: 💥 Check for merge conflicts
        language: system
        types: [text]
        entry: uv run check-merge-conflict
      - id: check-symlinks
        name: 🔗 Check for broken symlinks
        language: system
        types: [symlink]
        entry: uv run check-symlinks
      - id: check-toml
        name: ✅ Check TOML files
        language: system
        types: [toml]
        entry: uv run check-toml
      - id: check-yaml
        name: ✅ Check YAML files
        language: system
        types: [yaml]
        entry: uv run check-yaml
      - id: codespell
        name: ✅ Check code for common misspellings
        language: system
        types: [python]
        entry: uv run codespell
      - id: debug-statements
        name: 🪵  Debug Statements and imports (Python)
        language: system
        types: [python]
        entry: uv run debug-statement-hook
      - id: detect-private-key
        name: 🕵️  Detect Private Keys
        language: system
        types: [text]
        entry: uv run detect-private-key
      - id: end-of-file-fixer
        name: ⮐  Fix End of Files
        language: system
        types: [text]
        entry: uv run end-of-file-fixer
        stages: [pre-commit, pre-push, manual]
      - id: fix-byte-order-marker
        name: 🚏 Fix UTF-8 byte order marker
        language: system
        types: [text]
        entry: uv run fix-byte-order-marker
      - id: trailing-whitespace
        name: ✄  Trim Trailing Whitespace
        language: system
        types: [text]
        entry: uv run trailing-whitespace-fixer
        stages: [pre-commit, pre-push, manual]
      - id: yamllint
        name: 🎗  Check YAML files with yamllint
        language: system
        types: [yaml]
        entry: 'uv run yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}"'
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: "v0.9.0"
    hooks:
      - id: shellcheck
        name: ✅ Check Shell files
